name: authentication_repository
description: Repository to manage user authentication.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.4.3"

dependencies:
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen_runner: 5.4.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0